# Generated by Django 2.2.3 on 2020-01-31 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_STUDENT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('B', 'Bhawan'), ('I', 'Institute')], max_length=1)),
                ('post', models.CharField(choices=[('Technical Secretary', 'Technical Secretary'), ('Social and Cultural Secry', 'Social and Cultural Secretary'), ('Maintenance Secretary-1', 'Maintenance Secretary-1'), ('Maintenance Secretary-2', 'Maintenance Secretary-2'), ('Sports Secretary', 'Sports Secretary'), ('Mess Secretary', 'Mess Secretary'), ('G.S. Hostel Affairs', 'G.S. Hostel Affairs'), ('G.S. Academics Affairs(UG)', 'G.S. Academics Affairs(UG)'), ('G.S. Academics Affairs(PG)', 'G.S. Academics Affairs(PG)'), ('G.S. Technical Affairs', 'G.S. Technical Affairs'), ('G.S. Alumni Affairs', 'G.S. Alumni Affairs'), ('G.S. Sports Affairs', 'G.S. Sports Affairs'), ('G.S. Cultural Council', 'G.S. Cultural Council'), ('D.G.S. Hostel Affairs(UG)', 'D.G.S. Hostel Affairs(UG)'), ('D.G.S. Hostel Affairs(PG)', 'D.G.S. Hostel Affairs(PG)'), ('D.G.S. Hostel Affairs(GIRLS)', 'D.G.S. Hostel Affairs(GIRLS)')], max_length=30)),
                ('manifesto', models.FileField(null=True, upload_to=formula_one.utils.upload_to.UploadTo('electorate', 'electorate_files'))),
                ('approved', models.BooleanField(default=False)),
                ('video', models.FileField(null=True, upload_to=formula_one.utils.upload_to.UploadTo('electorate', 'electorate_files'))),
                ('resume', models.FileField(upload_to=formula_one.utils.upload_to.UploadTo('electorate', 'electorate_files'))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_STUDENT_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField(blank=True, default='', max_length=10000)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asker', to=settings.KERNEL_STUDENT_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='electorate.CandidateProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.KERNEL_STUDENT_MODEL)),
            ],
        ),
    ]
