# Generated by Django 2.2.3 on 2020-02-01 14:41

from django.db import migrations, models
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(null=True, upload_to=formula_one.utils.upload_to.UploadTo('electorate', 'electorate_files')),
        ),
    ]
