# Generated by Django 2.2.3 on 2020-02-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0003_auto_20200208_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='post',
            field=models.CharField(choices=[('G.S. Hostel Affairs', 'G.S. Hostel Affairs'), ('G.S. Academics Affairs(UG)', 'G.S. Academics Affairs(UG)'), ('G.S. Academics Affairs(PG)', 'G.S. Academics Affairs(PG)'), ('G.S. Technical Affairs', 'G.S. Technical Affairs'), ('G.S. Sports Affairs', 'G.S. Sports Affairs'), ('G.S. Cultural Council', 'G.S. Cultural Council'), ('G.S. Professional Affairs', 'G.S. Professional Affairs')], max_length=30),
        ),
    ]
