# Generated by Django 2.2.3 on 2020-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0005_auto_20200208_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='post',
            field=models.CharField(choices=[(0, 'G.S. Academics Affairs(UG)'), (1, 'G.S. Technical Affairs'), (2, 'G.S. Sports Affairs'), (3, 'G.S. Hostel Affairs'), (4, 'G.S. Cultural Council'), (5, 'G.S. Professional Affairs'), (6, 'G.S. Academics Affairs(PG)')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='post',
            field=models.CharField(choices=[(0, 'G.S. Academics Affairs(UG)'), (1, 'G.S. Technical Affairs'), (2, 'G.S. Sports Affairs'), (3, 'G.S. Hostel Affairs'), (4, 'G.S. Cultural Council'), (5, 'G.S. Professional Affairs'), (6, 'G.S. Academics Affairs(PG)')], max_length=30),
        ),
    ]
