# Generated by Django 2.2.3 on 2020-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0006_auto_20200210_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='post',
            field=models.CharField(choices=[('acad_ug', 'G.S. Academics Affairs(UG)'), ('tech', 'G.S. Technical Affairs'), ('sport', 'G.S. Sports Affairs'), ('hostel', 'G.S. Hostel Affairs'), ('cult', 'G.S. Cultural Council'), ('prof', 'G.S. Professional Affairs'), ('acad_pg', 'G.S. Academics Affairs(PG)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='post',
            field=models.CharField(choices=[('acad_ug', 'G.S. Academics Affairs(UG)'), ('tech', 'G.S. Technical Affairs'), ('sport', 'G.S. Sports Affairs'), ('hostel', 'G.S. Hostel Affairs'), ('cult', 'G.S. Cultural Council'), ('prof', 'G.S. Professional Affairs'), ('acad_pg', 'G.S. Academics Affairs(PG)')], max_length=30),
        ),
    ]
