# Generated by Django 2.2.3 on 2020-02-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0007_auto_20200210_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
